#!/usr/bin/env sh

# yabai config

# load scripting addition for macOS Big Sur
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# layout
yabai -m config layout                       bsp                   
yabai -m config window_placement             second_child 
yabai -m config window_gap                   0
yabai -m config window_shadow                off
yabai -m config window_border                off

