# Personal Alacritty Configuration
# Author: Francisco Cornejo-Garcia (@franciscornejog)

live_config_reload = true

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[colors]
draw_bold_text_with_bright_colors = false

[colors.normal]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[mouse]
hide_when_typing = true

[window]
option_as_alt = "Both"
decorations = "none"
dynamic_padding = true
padding = { x = 1, y = 1 }
position = { x = 0, y = 0 }
