add_newline = false
format = """
$username$hostname$localip$directory\
$git_branch$git_commit$git_state$git_status\
$custom$sudo$character"""
right_format = "$memory_usage$cmd_duration"

[character]
success_symbol = "[:](bold white)"
error_symbol = "[:](bold red)"
vimcmd_symbol = "[:](bold purple)"

[cmd_duration]
format = '\[[$duration]($style)\]'

[directory]
read_only = " ro"
format = "[$path](bold green)[$read_only]($read_only_style)"

[git_branch]
format = ' \([$branch](white)'

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">${count}"
behind = "<${count}"
diverged = "<${ahead_count}>${behind_count}"
modified = "*"
stashed = "#"
deleted = ""
format = '([$all_status$ahead_behind](#fe8019))\)'

[memory_usage]
format = '\[[$ram_pct(|$swap_pct)]($style)\]'
disabled = false

[username]
format = '\[[$user]($style)\]'
